name = "cors_builder"
version = "2.0.1"

description = "A CORS Builder, performing validation and injection of CORS for misp, wisp and any framework!"
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "cors-builder"}

[dependencies]
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.0.0 and < 2.0.0"
mist = ">= 1.2.0 and < 3.0.0"

[dev-dependencies]
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
